//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 03:48:30 PM EST 
//


package com.paypal.credit.workflowcommand.workflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for baseProcessorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="baseProcessorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="parallel" type="{http://credit.paypal.com/v1/schema/workflow}parallelType"/>
 *         &lt;element name="serial" type="{http://credit.paypal.com/v1/schema/workflow}serialType"/>
 *         &lt;element name="conditional" type="{http://credit.paypal.com/v1/schema/workflow}conditionalType"/>
 *         &lt;element name="processor" type="{http://credit.paypal.com/v1/schema/workflow}processorType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "baseProcessorType", propOrder = {
    "parallelOrSerialOrConditional"
})
@XmlSeeAlso({
    ParallelType.class,
    StartType.class,
    SerialType.class
})
public class BaseProcessorType {

    @XmlElements({
        @XmlElement(name = "parallel", type = ParallelType.class),
        @XmlElement(name = "serial", type = SerialType.class),
        @XmlElement(name = "conditional", type = ConditionalType.class),
        @XmlElement(name = "processor", type = ProcessorType.class)
    })
    protected List<Object> parallelOrSerialOrConditional;

    /**
     * Gets the value of the parallelOrSerialOrConditional property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parallelOrSerialOrConditional property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParallelOrSerialOrConditional().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParallelType }
     * {@link SerialType }
     * {@link ConditionalType }
     * {@link ProcessorType }
     * 
     * 
     */
    public List<Object> getParallelOrSerialOrConditional() {
        if (parallelOrSerialOrConditional == null) {
            parallelOrSerialOrConditional = new ArrayList<Object>();
        }
        return this.parallelOrSerialOrConditional;
    }

}
