//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.16 at 04:53:05 PM EST 
//


package com.paypal.credit.workflowcommand.workflow;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for conditionalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="conditionalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parallel" type="{http://credit.paypal.com/v1/schema/workflow}parallelType" minOccurs="0"/>
 *         &lt;element name="serial" type="{http://credit.paypal.com/v1/schema/workflow}serialType" minOccurs="0"/>
 *         &lt;element name="conditional" type="{http://credit.paypal.com/v1/schema/workflow}conditionalType" minOccurs="0"/>
 *         &lt;element name="processor" type="{http://credit.paypal.com/v1/schema/workflow}processorType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="contextField" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fieldValue" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "conditionalType", propOrder = {
    "parallel",
    "serial",
    "conditional",
    "processor"
})
public class ConditionalType {

    protected ParallelType parallel;
    protected SerialType serial;
    protected ConditionalType conditional;
    protected ProcessorType processor;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "contextField", required = true)
    protected String contextField;
    @XmlAttribute(name = "fieldValue", required = true)
    protected String fieldValue;

    /**
     * Gets the value of the parallel property.
     * 
     * @return
     *     possible object is
     *     {@link ParallelType }
     *     
     */
    public ParallelType getParallel() {
        return parallel;
    }

    /**
     * Sets the value of the parallel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParallelType }
     *     
     */
    public void setParallel(ParallelType value) {
        this.parallel = value;
    }

    /**
     * Gets the value of the serial property.
     * 
     * @return
     *     possible object is
     *     {@link SerialType }
     *     
     */
    public SerialType getSerial() {
        return serial;
    }

    /**
     * Sets the value of the serial property.
     * 
     * @param value
     *     allowed object is
     *     {@link SerialType }
     *     
     */
    public void setSerial(SerialType value) {
        this.serial = value;
    }

    /**
     * Gets the value of the conditional property.
     * 
     * @return
     *     possible object is
     *     {@link ConditionalType }
     *     
     */
    public ConditionalType getConditional() {
        return conditional;
    }

    /**
     * Sets the value of the conditional property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConditionalType }
     *     
     */
    public void setConditional(ConditionalType value) {
        this.conditional = value;
    }

    /**
     * Gets the value of the processor property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessorType }
     *     
     */
    public ProcessorType getProcessor() {
        return processor;
    }

    /**
     * Sets the value of the processor property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessorType }
     *     
     */
    public void setProcessor(ProcessorType value) {
        this.processor = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the contextField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextField() {
        return contextField;
    }

    /**
     * Sets the value of the contextField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextField(String value) {
        this.contextField = value;
    }

    /**
     * Gets the value of the fieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldValue() {
        return fieldValue;
    }

    /**
     * Sets the value of the fieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldValue(String value) {
        this.fieldValue = value;
    }

}
