//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 03:48:30 PM EST 
//


package com.paypal.credit.workflowcommand.workflow;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.paypal.credit.workflow package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Workflow_QNAME = new QName("http://credit.paypal.com/v1/schema/workflow", "workflow");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.paypal.credit.workflow
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WorkflowType }
     * 
     */
    public WorkflowType createWorkflowType() {
        return new WorkflowType();
    }

    /**
     * Create an instance of {@link ConditionalType }
     * 
     */
    public ConditionalType createConditionalType() {
        return new ConditionalType();
    }

    /**
     * Create an instance of {@link ParallelType }
     * 
     */
    public ParallelType createParallelType() {
        return new ParallelType();
    }

    /**
     * Create an instance of {@link StartType }
     * 
     */
    public StartType createStartType() {
        return new StartType();
    }

    /**
     * Create an instance of {@link SerialType }
     * 
     */
    public SerialType createSerialType() {
        return new SerialType();
    }

    /**
     * Create an instance of {@link ProcessorType }
     * 
     */
    public ProcessorType createProcessorType() {
        return new ProcessorType();
    }

    /**
     * Create an instance of {@link OptionsType }
     * 
     */
    public OptionsType createOptionsType() {
        return new OptionsType();
    }

    /**
     * Create an instance of {@link BaseProcessorType }
     * 
     */
    public BaseProcessorType createBaseProcessorType() {
        return new BaseProcessorType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkflowType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://credit.paypal.com/v1/schema/workflow", name = "workflow")
    public JAXBElement<WorkflowType> createWorkflow(WorkflowType value) {
        return new JAXBElement<WorkflowType>(_Workflow_QNAME, WorkflowType.class, null, value);
    }

}
