//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.17 at 10:35:08 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://credit.paypal.com/v1/schema/ctx", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.paypal.credit.context.xml;
