//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.09 at 04:51:22 PM EST 
//


package com.paypal.credit.context.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.paypal.credit.context.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Beans_QNAME = new QName("http://credit.paypal.com/v1/schema/ctx", "beans");
    private final static QName _Value_QNAME = new QName("http://credit.paypal.com/v1/schema/ctx", "value");
    private final static QName _Bean_QNAME = new QName("http://credit.paypal.com/v1/schema/ctx", "bean");
    private final static QName _List_QNAME = new QName("http://credit.paypal.com/v1/schema/ctx", "list");
    private final static QName _Ref_QNAME = new QName("http://credit.paypal.com/v1/schema/ctx", "ref");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.paypal.credit.context.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BeansType }
     * 
     */
    public BeansType createBeansType() {
        return new BeansType();
    }

    /**
     * Create an instance of {@link BeanType }
     * 
     */
    public BeanType createBeanType() {
        return new BeanType();
    }

    /**
     * Create an instance of {@link ListType }
     * 
     */
    public ListType createListType() {
        return new ListType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link ConstructorArgType }
     * 
     */
    public ConstructorArgType createConstructorArgType() {
        return new ConstructorArgType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BeansType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://credit.paypal.com/v1/schema/ctx", name = "beans")
    public JAXBElement<BeansType> createBeans(BeansType value) {
        return new JAXBElement<BeansType>(_Beans_QNAME, BeansType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://credit.paypal.com/v1/schema/ctx", name = "value")
    public JAXBElement<String> createValue(String value) {
        return new JAXBElement<String>(_Value_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BeanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://credit.paypal.com/v1/schema/ctx", name = "bean")
    public JAXBElement<BeanType> createBean(BeanType value) {
        return new JAXBElement<BeanType>(_Bean_QNAME, BeanType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://credit.paypal.com/v1/schema/ctx", name = "list")
    public JAXBElement<ListType> createList(ListType value) {
        return new JAXBElement<ListType>(_List_QNAME, ListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://credit.paypal.com/v1/schema/ctx", name = "ref")
    public JAXBElement<ReferenceType> createRef(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_Ref_QNAME, ReferenceType.class, null, value);
    }

}
