//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.18 at 12:02:35 PM EST 
//


package com.paypal.credit.workflowcommand.workflow.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 A ConditionalControllerType must include one processor which is executed iff
 *                 the context field value is equal to the given value at the point of execution
 *                 of the workflow.
 *             
 * 
 * <p>Java class for ConditionalControllerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConditionalControllerType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://credit.paypal.com/v1/schema/workflow}BaseProcessorType">
 *       &lt;sequence>
 *         &lt;element ref="{http://credit.paypal.com/v1/schema/workflow}processor"/>
 *       &lt;/sequence>
 *       &lt;attribute name="context-field" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="field-value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConditionalControllerType", propOrder = {
    "processor"
})
public class ConditionalControllerType
    extends BaseProcessorType
{

    @XmlElementRef(name = "processor", namespace = "http://credit.paypal.com/v1/schema/workflow", type = JAXBElement.class)
    protected JAXBElement<? extends BaseProcessorType> processor;
    @XmlAttribute(name = "context-field", required = true)
    protected String contextField;
    @XmlAttribute(name = "field-value", required = true)
    protected String fieldValue;

    /**
     * Gets the value of the processor property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link SerialControllerType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BusinessProcessorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConditionalControllerType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ParallelControllerType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BaseProcessorType }{@code >}
     *     
     */
    public JAXBElement<? extends BaseProcessorType> getProcessor() {
        return processor;
    }

    /**
     * Sets the value of the processor property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link SerialControllerType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BusinessProcessorType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ConditionalControllerType }{@code >}
     *     {@link JAXBElement }{@code <}{@link ParallelControllerType }{@code >}
     *     {@link JAXBElement }{@code <}{@link BaseProcessorType }{@code >}
     *     
     */
    public void setProcessor(JAXBElement<? extends BaseProcessorType> value) {
        this.processor = value;
    }

    /**
     * Gets the value of the contextField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextField() {
        return contextField;
    }

    /**
     * Sets the value of the contextField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextField(String value) {
        this.contextField = value;
    }

    /**
     * Gets the value of the fieldValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldValue() {
        return fieldValue;
    }

    /**
     * Sets the value of the fieldValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldValue(String value) {
        this.fieldValue = value;
    }

}
