package com.paypal.credit.core.commandprovider;

import com.paypal.credit.core.commandprocessor.Command;
import com.paypal.credit.core.commandprocessor.RoutingToken;
import com.paypal.credit.core.commandprovider.exceptions.CommandInstantiationException;
import com.paypal.credit.core.commandprovider.exceptions.CommandProviderException;
import com.paypal.credit.core.commandprovider.exceptions.InvalidTokenException;
import com.paypal.credit.core.commandprovider.exceptions.MultipleCommandImplementationsException;
import com.paypal.credit.core.semantics.CommandClassSemantics;

/**
 * THe definition of a CommandProvider
 */
public interface CommandProvider {
    /**
     * The publisher can be used to select a specific CommandProvider if
     * there are multiple Command implementations available.
     * @return
     */
    String getPublisher();

    /**
     * Find a Command meeting the semantics, that can be instantiated with the
     * parameter types and whose invoke method returns the resultType.
     * The RoutingToken may be used to select or initialize the Command implementation.
     * @param routingToken
     * @param commandClassSemantics
     * @param parameters
     * @param resultType
     * @return
     * @throws CommandProviderException
     */
    CommandInstantiationToken findCommand(
            final RoutingToken routingToken,
            final CommandClassSemantics commandClassSemantics,
            final Class<?>[] parameters,
            final Class<?> resultType)
            throws CommandProviderException;

    /**
     * Create a Command from a CommandInstantiationToken that was previously generated by this
     * Provider and using the given parameters to instantiate the instance.
     * @param commandInstantiationToken
     * @param parameters
     * @return
     * @throws CommandProviderException
     */
    Command<?> createCommand(
            final CommandInstantiationToken commandInstantiationToken,
            final Object[] parameters)
            throws CommandProviderException;

}
