//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 03:20:09 PM EST 
//


package com.paypal.credit.workflow.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.paypal.credit.workflow.schema package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BusinessProcessor_QNAME = new QName("http://credit.paypal.com/v1/schema/workflow", "business-processor");
    private final static QName _Workflow_QNAME = new QName("http://credit.paypal.com/v1/schema/workflow", "workflow");
    private final static QName _SerialController_QNAME = new QName("http://credit.paypal.com/v1/schema/workflow", "serial-controller");
    private final static QName _ParallelController_QNAME = new QName("http://credit.paypal.com/v1/schema/workflow", "parallel-controller");
    private final static QName _ConditionalController_QNAME = new QName("http://credit.paypal.com/v1/schema/workflow", "conditional-controller");
    private final static QName _Processor_QNAME = new QName("http://credit.paypal.com/v1/schema/workflow", "processor");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.paypal.credit.workflow.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ParallelControllerType }
     * 
     */
    public ParallelControllerType createParallelControllerType() {
        return new ParallelControllerType();
    }

    /**
     * Create an instance of {@link ProcessList }
     * 
     */
    public ProcessList createProcessList() {
        return new ProcessList();
    }

    /**
     * Create an instance of {@link WorkflowType }
     * 
     */
    public WorkflowType createWorkflowType() {
        return new WorkflowType();
    }

    /**
     * Create an instance of {@link SerialControllerType }
     * 
     */
    public SerialControllerType createSerialControllerType() {
        return new SerialControllerType();
    }

    /**
     * Create an instance of {@link BusinessProcessorType }
     * 
     */
    public BusinessProcessorType createBusinessProcessorType() {
        return new BusinessProcessorType();
    }

    /**
     * Create an instance of {@link ConditionalControllerType }
     * 
     */
    public ConditionalControllerType createConditionalControllerType() {
        return new ConditionalControllerType();
    }

    /**
     * Create an instance of {@link OptionType }
     * 
     */
    public OptionType createOptionType() {
        return new OptionType();
    }

    /**
     * Create an instance of {@link OptionsType }
     * 
     */
    public OptionsType createOptionsType() {
        return new OptionsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessProcessorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://credit.paypal.com/v1/schema/workflow", name = "business-processor", substitutionHeadNamespace = "http://credit.paypal.com/v1/schema/workflow", substitutionHeadName = "processor")
    public JAXBElement<BusinessProcessorType> createBusinessProcessor(BusinessProcessorType value) {
        return new JAXBElement<BusinessProcessorType>(_BusinessProcessor_QNAME, BusinessProcessorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WorkflowType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://credit.paypal.com/v1/schema/workflow", name = "workflow")
    public JAXBElement<WorkflowType> createWorkflow(WorkflowType value) {
        return new JAXBElement<WorkflowType>(_Workflow_QNAME, WorkflowType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SerialControllerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://credit.paypal.com/v1/schema/workflow", name = "serial-controller", substitutionHeadNamespace = "http://credit.paypal.com/v1/schema/workflow", substitutionHeadName = "processor")
    public JAXBElement<SerialControllerType> createSerialController(SerialControllerType value) {
        return new JAXBElement<SerialControllerType>(_SerialController_QNAME, SerialControllerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParallelControllerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://credit.paypal.com/v1/schema/workflow", name = "parallel-controller", substitutionHeadNamespace = "http://credit.paypal.com/v1/schema/workflow", substitutionHeadName = "processor")
    public JAXBElement<ParallelControllerType> createParallelController(ParallelControllerType value) {
        return new JAXBElement<ParallelControllerType>(_ParallelController_QNAME, ParallelControllerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConditionalControllerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://credit.paypal.com/v1/schema/workflow", name = "conditional-controller", substitutionHeadNamespace = "http://credit.paypal.com/v1/schema/workflow", substitutionHeadName = "processor")
    public JAXBElement<ConditionalControllerType> createConditionalController(ConditionalControllerType value) {
        return new JAXBElement<ConditionalControllerType>(_ConditionalController_QNAME, ConditionalControllerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BaseProcessorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://credit.paypal.com/v1/schema/workflow", name = "processor")
    public JAXBElement<BaseProcessorType> createProcessor(BaseProcessorType value) {
        return new JAXBElement<BaseProcessorType>(_Processor_QNAME, BaseProcessorType.class, null, value);
    }

}
