//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 03:20:09 PM EST 
//


package com.paypal.credit.workflow.schema;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://credit.paypal.com/v1/schema/workflow}processor" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processor"
})
@XmlRootElement(name = "process-list")
public class ProcessList {

    @XmlElementRef(name = "processor", namespace = "http://credit.paypal.com/v1/schema/workflow", type = JAXBElement.class, required = false)
    protected List<JAXBElement<? extends BaseProcessorType>> processor;

    /**
     * Gets the value of the processor property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the processor property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProcessor().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link BusinessProcessorType }{@code >}
     * {@link JAXBElement }{@code <}{@link BaseProcessorType }{@code >}
     * {@link JAXBElement }{@code <}{@link ConditionalControllerType }{@code >}
     * {@link JAXBElement }{@code <}{@link ParallelControllerType }{@code >}
     * {@link JAXBElement }{@code <}{@link SerialControllerType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends BaseProcessorType>> getProcessor() {
        if (processor == null) {
            processor = new ArrayList<JAXBElement<? extends BaseProcessorType>>();
        }
        return this.processor;
    }

}
