//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.04 at 03:20:09 PM EST 
//


package com.paypal.credit.workflow.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 A WorkflowType must include a context class name and at least one
 *                 processor.
 *             
 * 
 * <p>Java class for WorkflowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WorkflowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://credit.paypal.com/v1/schema/workflow}process-list"/>
 *       &lt;/sequence>
 *       &lt;attribute name="context-class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WorkflowType", propOrder = {
    "processList"
})
public class WorkflowType {

    @XmlElement(name = "process-list", required = true)
    protected ProcessList processList;
    @XmlAttribute(name = "context-class", required = true)
    protected String contextClass;

    /**
     * Gets the value of the processList property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessList }
     *     
     */
    public ProcessList getProcessList() {
        return processList;
    }

    /**
     * Sets the value of the processList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessList }
     *     
     */
    public void setProcessList(ProcessList value) {
        this.processList = value;
    }

    /**
     * Gets the value of the contextClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextClass() {
        return contextClass;
    }

    /**
     * Sets the value of the contextClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextClass(String value) {
        this.contextClass = value;
    }

}
